const assert = require('node:assert/strict');
module.exports = async function conversationUI(page) {
  await page.evaluate(() => { applyChatMode('casual'); switchModule('chat'); });
  await page.locator('#side-new').click();
  await page.waitForFunction(() => sessionId && !taskLoading);
  const first = await page.evaluate(() => sessionId);
  await page.locator(`.task-row[data-task="${first}"]`).click({button:'right'});
  await page.getByRole('menuitem', {name:'重命名', exact:true}).click();
  await page.locator('#task-title-input').fill('周末出行计划');
  await page.locator('#task-confirm').click();
  await page.locator('#task-dialog').waitFor({state:'hidden'});
  await page.locator('.task-name').filter({hasText:'周末出行计划'}).waitFor();
  await page.locator('#chat-input').fill('这是一段尚未发送的草稿');
  await page.locator('#side-new').click();
  await page.waitForFunction(id => sessionId !== id && !taskLoading, first);
  const second = await page.evaluate(() => sessionId);
  assert.equal(await page.locator('#chat-input').inputValue(), '');
  await page.locator(`.task-row[data-task="${first}"] .task-select`).click();
  await page.waitForFunction(id => sessionId === id && !taskLoading, first);
  assert.equal(await page.locator('#chat-input').inputValue(), '这是一段尚未发送的草稿');
  await page.locator('#side-search').fill('周末');
  assert.equal(await page.locator('.task-row').count(), 1);
  assert.ok((await page.locator('#side-search').boundingBox()).width > 150);
  await page.locator('.task-row').click({button:'right'});
  await page.getByRole('menuitem', {name:'置顶对话',exact:true}).click();
  await page.locator('.task-pin').waitFor();
  await page.locator('#side-search').fill('');
  // Persist a real tool conversation and then restore it through the sidebar.
  await page.evaluate(async id => {
    await api('/api/chat', 'POST', {user_id:userId,session_id:id,text:'提醒我10分钟后喝水'});
    await selectTask(id); await refreshTasks();
  }, first);
  assert.match(await page.locator('#chat-box').textContent(), /喝水/);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(id => sessionId === id && !taskLoading, first);
  assert.match(await page.locator('#chat-box').textContent(), /喝水/);
  await page.locator(`.task-row[data-task="${second}"]`).click({button:'right'});
  await page.getByRole('menuitem', {name:'删除对话',exact:true}).click();
  await page.locator('#task-confirm').click();
  await page.locator('#task-dialog').waitFor({state:'hidden'});
  await page.locator(`.task-row[data-task="${second}"]`).waitFor({state:'detached'});
  await page.evaluate(() => {
    addMsg('user', '今天有点累。');
    handleWSMessage({type:'thinking',step:1,total:1,title:'观察',text:'诊断内容'});
    handleWSMessage({type:'reply_delta',text:'辛苦了，先休息一会儿吧。'});
    handleWSMessage({type:'reply_done',reply:'辛苦了，先休息一会儿吧。',confidence:{score:99,level:'高'},sources:[]});
  });
  assert.equal(await page.locator('.think-panel, .reply-details, .think-conf').count(), 0);
  assert.equal(await page.getByRole('button',{name:'复制',exact:true}).count(), 1);
  await page.evaluate(() => updateReasoning({reasoning_supported:true,model:'o3-mini'}));
  assert.equal(await page.locator('#reasoning-model').textContent(), 'o3-mini');
  await page.locator('#reasoning-control summary').click();
  assert.ok((await page.locator('.reasoning-popover').boundingBox()).width <= 240);
  assert.equal((await page.locator('#reasoning-range').boundingBox()).height, 36);
  assert.equal(await page.locator('.reasoning-popover').evaluate(e => getComputedStyle(e).backgroundColor), 'rgb(255, 255, 255)');
  await page.locator('#reasoning-range').focus();
  await page.keyboard.press('Home');
  const slider = await page.locator('#reasoning-range').boundingBox();
  await page.mouse.move(slider.x + 14, slider.y + slider.height / 2);
  await page.mouse.down();
  await page.mouse.move(slider.x + slider.width * .44, slider.y + slider.height / 2, {steps:8});
  const fractional = Number(await page.locator('#reasoning-range').inputValue());
  assert.ok(fractional > 1 && fractional < 2 && fractional !== Math.round(fractional));
  await page.mouse.move(slider.x + slider.width - 14, slider.y + slider.height / 2, {steps:8});
  await page.mouse.up();
  assert.equal(await page.locator('#reasoning-label').textContent(), '高');
  assert.equal(await page.evaluate(() => reasoningEffort()), 'high');
  assert.equal(await page.locator('.reasoning-popover').isVisible(), true);
  await page.keyboard.press('ArrowLeft');
  assert.equal(await page.locator('#reasoning-current').textContent(), '中');
  assert.equal(await page.evaluate(() => reasoningEffort()), 'medium');
  assert.equal(await page.evaluate(() => localStorage.getItem('ylb_reasoning')), '2');
  await page.screenshot({path:'ui-conversation-workspace.png'});
  await page.locator('.reasoning-popover').screenshot({path:'ui-reasoning-slider.png'});
  await page.locator('#reasoning-reset').click();
  assert.equal(await page.locator('#reasoning-range').inputValue(), '0');
  assert.equal(await page.evaluate(() => reasoningEffort()), null);
  await page.locator('#chat-input').click();
  assert.equal(await page.locator('.reasoning-popover').isVisible(), false);
  await page.locator('#reasoning-control summary').click();
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.reasoning-popover').isVisible(), false);
  await page.evaluate(() => checkConnectionOnLoad({reasoning_supported:false,model:'deepseek-chat',configured:false}));
  assert.equal(await page.locator('#reasoning-model').textContent(), 'deepseek-chat');
  await page.locator('#reasoning-control summary').click();
  assert.equal(await page.locator('#reasoning-range').isDisabled(), true);
  assert.equal(await page.evaluate(() => reasoningEffort()), null);
  await page.keyboard.press('Escape');
  await page.locator('#reasoning-control summary').click();
  await page.locator('#reasoning-model').click();
  await page.locator('#settings-mask.show').waitFor();
  assert.equal(await page.locator('#settings-close').isVisible(), true);
  const modelChoice = await page.evaluate(() => {
    document.getElementById('set-llm-provider').value = 'deepseek';
    document.getElementById('set-llm-provider').dispatchEvent(new Event('change'));
    const actual = document.getElementById('set-llm-model').value;
    const expected = SET_CATALOG.llm.find(provider => provider.id === 'deepseek').models[0].id;
    fillSetModels('llm', 'user-chosen-model');
    return {actual, expected, custom:document.getElementById('set-llm-model').value};
  });
  assert.equal(modelChoice.actual, modelChoice.expected);
  assert.equal(modelChoice.custom, 'user-chosen-model');
  assert.equal(await page.locator('#show-reply-details').isVisible(), false);
  await page.screenshot({path:'ui-settings-refined.png'});
  await page.setViewportSize({width:800,height:600});
  await page.evaluate(() => { for(let i=0;i<8;i++) document.getElementById('font-larger').click(); });
  await page.evaluate(() => {
    const panel=document.querySelector('#settings-mask .modal-panel');
    panel.querySelectorAll('details').forEach(el => el.open = true); panel.scrollTop=panel.scrollHeight;
  });
  const close = await page.locator('#settings-close').boundingBox();
  assert.ok(close.y >= 0 && close.y + close.height <= 600);
  await page.screenshot({path:'ui-settings-large-font.png'});
  await page.locator('#settings-close').click();
  await page.locator('#settings-mask').waitFor({state:'hidden'});
  await page.locator('#task-toggle').click();
  await page.locator('.task-row').first().waitFor({state:'visible'});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({path:'ui-tasks-compact.png'});
  await page.keyboard.press('Escape');
  await page.locator('#font-reset').click();
  await page.setViewportSize({width:1280,height:900});
  // Exercise the front-end dead-connection watchdog without sending a real model request.
  await page.evaluate(() => {
    pendingChatText='保留超时草稿'; chatSending=true; activeChatRequest='watchdog';
    document.getElementById('chat-input').value=''; armChatWait(60);
  });
  await page.waitForFunction(() => !chatSending);
  assert.equal(await page.locator('#chat-input').inputValue(), '保留超时草稿');
  assert.equal(await page.locator('#chat-retry').isVisible(), true);
  // Exercise the real note canvas: create, drag, search, zoom, delete/undo and reload.
  await page.evaluate(() => switchModule('canvas'));
  await page.locator('#note-canvas').waitFor({state:'visible'});
  await page.waitForFunction(() => document.getElementById('board-status').textContent.includes('保存') || document.getElementById('board-status').textContent.includes('加载'));
  await page.locator('#board-add').click();
  await page.locator('#board-editor').waitFor({state:'visible'});
  await page.locator('#board-text').fill('比赛灵感：让便签和对话一起工作');
  await page.locator('input[name="board-color"][value="yellow"]').check();
  await page.locator('#board-editor-save').click();
  await page.locator('.board-card').waitFor();
  assert.equal(await page.locator('.board-card.yellow').count(), 1);
  const beforeDrag = await page.locator('.board-card').boundingBox();
  await page.mouse.move(beforeDrag.x + 100, beforeDrag.y + 75);
  await page.mouse.down();
  await page.mouse.move(beforeDrag.x + 170, beforeDrag.y + 125, {steps:8});
  await page.mouse.up();
  await page.waitForTimeout(650);
  assert.equal(await page.locator('#board-status').textContent(), '已保存');
  await page.locator('#board-search-toggle').click();
  await page.locator('#board-search').fill('比赛灵感');
  assert.equal(await page.locator('.board-side-card').count(), 1);
  await page.locator('#board-zoom-in').click();
  assert.equal(await page.locator('#board-zoom-value').textContent(), '110%');
  await page.locator('.board-card').click();
  await page.locator('#board-delete').click();
  assert.equal(await page.locator('.board-card').count(), 0);
  await page.locator('#board-undo').click();
  assert.equal(await page.locator('.board-card').count(), 1);
  await page.waitForFunction(() => document.getElementById('board-status').textContent === '已保存', {timeout: 10000});
  assert.equal(await page.evaluate(async () => (await fetch(`/api/users/${userId}/canvas`)).json()).then(data => data.cards.length), 1);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(() => Number.isInteger(userId) && userId > 0, {timeout: 15000});
  await page.evaluate(() => switchModule('canvas'));
  await page.waitForFunction(() => document.getElementById('board-status')?.textContent?.includes('保存'), {timeout: 10000});
  await page.locator('.board-card').waitFor();
  assert.equal((await page.locator('.board-card').textContent()).includes('比赛灵感'), true);
  await page.screenshot({path:'ui-note-canvas.png'});
  return {context_menu_crud_search_pin:'passed', independent_drafts_history_restore:'passed', hidden_diagnostics:'passed', reasoning_slider:'passed', settings_close_at_180_percent:'passed', compact_task_navigation:'passed', unresponsive_watchdog_draft_retry:'passed', note_canvas_create_drag_search_zoom_reload:'passed'};
};
