const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = [], external = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.route('**/*', route => {
    if (!route.request().url().startsWith(process.argv[2])) {
      external.push(route.request().url()); return route.abort();
    }
    return route.continue();
  });
  try {
    const start = Date.now();
    await page.goto(process.argv[2], { waitUntil: 'domcontentloaded' });
    await page.locator('#boot-screen').waitFor({ state: 'hidden', timeout: 9000 });
    const firstScreenMs = Date.now() - start;
    await page.locator('#welcome-name').fill('界面测试');
    await page.locator('#welcome-go').click();
    await page.locator('#welcome-mask').waitFor({ state:'hidden' });
    await page.waitForFunction(() => ws && ws.readyState === 1);
    await page.locator('#chat-input').fill('你好');
    await page.locator('#btn-send').click();
    await page.waitForFunction(() => !chatSending && document.getElementById('chat-input').value === '你好');
    assert.match(await page.locator('#chat-notice').textContent(), /API Key/);
    assert.equal(await page.locator('#chat-configure').isVisible(), true);
    assert.equal(await page.locator('#btn-send').isEnabled(), true);
    await page.screenshot({path:'ui-api-required.png'});
    await page.locator('#chat-configure').click();
    await page.locator('#settings-mask.show').waitFor();
    await page.evaluate(() => closeSettings());
    await page.evaluate(() => ws.close());
    await page.waitForFunction(() => ws.readyState !== 1);
    await page.locator('#btn-send').click();
    assert.match(await page.locator('#chat-notice').textContent(), /连接/);
    assert.equal(await page.locator('#chat-input').inputValue(), '你好');
    await page.locator('#chat-input').fill('');
    assert.equal(await page.locator('body').evaluate(e => getComputedStyle(e).fontSize), '18px');
    await page.locator('#font-larger').click();
    assert.equal(await page.locator('#font-percent').textContent(), '110%');
    assert.ok(Math.abs(await page.locator('#chat-input').evaluate(e => parseFloat(getComputedStyle(e).fontSize)) - 18.7) < .01);
    await page.reload({ waitUntil:'domcontentloaded' });
    await page.locator('#boot-screen').waitFor({ state:'hidden' });
    assert.equal(await page.locator('#font-percent').textContent(), '110%');
    await page.evaluate(() => applyChatMode('elderly'));
    assert.ok(Math.abs(await page.locator('.msg').first().evaluate(e => parseFloat(getComputedStyle(e).fontSize)) - 26.4) < .01);
    await page.evaluate(() => switchModule('imggen'));
    assert.equal(await page.locator('#font-larger').isVisible(), true);
    await page.locator('#font-reset').click();
    assert.equal(await page.locator('#font-percent').textContent(), '100%');
    for (let i=0;i<8;i++) await page.locator('#font-larger').click();
    assert.equal(await page.locator('#font-larger').isDisabled(), true);
    await page.setViewportSize({width:800,height:600});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.equal(await page.locator('#font-smaller').isVisible(), true);
    for (let i=0;i<11;i++) await page.locator('#font-smaller').click();
    assert.equal(await page.locator('#font-percent').textContent(), '70%');
    assert.equal(await page.locator('#font-smaller').isDisabled(), true);
    await page.locator('#font-reset').click();
    await page.setViewportSize({width:1280,height:900});
    await page.evaluate(() => switchModule('chat'));
    assert.ok((await page.locator('#font-larger').boundingBox()).height <= 32);
    assert.ok((await page.locator('#btn-send').boundingBox()).height <= 40);
    assert.equal(await page.locator('.msg').first().evaluate(e => getComputedStyle(e).fontSize), '24px');
    await page.screenshot({ path: 'ui-desktop.png' });
    await page.setViewportSize({ width:800, height:600 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: 'ui-compact.png' });
    await page.setViewportSize({ width:1280, height:900 });
    await page.evaluate(() => openSettings());
    await page.locator('#set-llm-description').waitFor();
    assert.ok((await page.locator('#set-llm-description').textContent()).length > 5);
    await page.evaluate(() => closeSettings());
    await page.evaluate(() => switchModule('imggen'));
    await page.locator('#img-backends [data-backend="custom"]').click();
    await page.locator('#img-model-input').fill('acceptance-model');
    await page.locator('#img-base-url').fill('https://example.invalid/v1');
    await page.locator('#img-prompt').fill('一只猫');
    let payload;
    await page.route('**/api/image/generations', route => {
      payload = route.request().postDataJSON();
      return route.fulfill({ status:400, contentType:'application/json', body:JSON.stringify({detail:{message:'测试失败恢复按钮',solution:'test'}}) });
    });
    await page.locator('#img-go').click();
    await page.waitForFunction(() => !document.getElementById('img-go').disabled);
    assert.equal(payload.provider_id, 'custom');
    assert.equal(payload.model, 'acceptance-model');
    assert.equal(payload.base_url, 'https://example.invalid/v1');
    const avatar = await page.evaluate(() => {
      const calls=[];
      const sdk=Object.fromEntries(['listen','think','interactiveidle','destroy','speak'].map(m=>[m,(...a)=>calls.push([m,...a])]));
      avatarBridge.attach(sdk);
      avatarBridge.handle({type:'emotion'});
      avatarBridge.handle({type:'reply_delta',text:'这是第一段内容。'.repeat(10)});
      avatarBridge.handle({type:'reply_done',reply:'这是第一段内容。'.repeat(10)});
      avatarBridge.handle({type:'interrupted'});
      avatarBridge.detach();
      return calls;
    });
    const speaks=avatar.filter(c=>c[0]==='speak');
    assert.equal(speaks[0][2],true);
    assert.equal(speaks.at(-1)[3],true);
    assert.equal(speaks.map(c=>c[1]).join(''),'这是第一段内容。'.repeat(10));
    const conversation = await require('./conversation_ui.cjs')(page);
    assert.deepEqual(errors,[]);
    assert.deepEqual(external,[]);
    console.log(JSON.stringify({first_screen_ms:firstScreenMs, conversation, missing_api_websocket_settings_and_draft:'passed', disconnected_send_feedback:'passed', compact_buttons:'passed', typography:'passed', font_controls_persistence_limits_and_modes:'passed', compact_layout:'passed', image_selection_and_error_recovery:'passed', avatar_stream_and_interrupt:'passed', javascript_errors:errors, external_startup_requests:external}));
  } finally { await browser.close(); }
})().catch(e => {console.error(e);process.exit(1);});
